import 'package:flutter/material.dart';
import 'package:gymnastic_center/presentation/widgets/shared/gymnastic_text_form_field/gymnastic_text_input_decoration.dart';

class GymnasticTextFormField extends TextFormField {
  GymnasticTextFormField({
    super.key,
    super.controller,
    super.autocorrect,
    super.autofillHints,
    super.autofocus,
    super.autovalidateMode,
    super.buildCounter,
    super.canRequestFocus,
    super.clipBehavior,
    super.contentInsertionConfiguration,
    super.contextMenuBuilder,
    super.cursorColor,
    // super.cursorErrorColor,
    super.cursorHeight,
    super.cursorOpacityAnimates,
    super.cursorRadius,
    super.cursorWidth,
    super.dragStartBehavior,
    super.enableIMEPersonalizedLearning,
    super.enableInteractiveSelection,
    super.enableSuggestions,
    super.enabled,
    super.expands,
    super.focusNode,
    super.initialValue,
    super.inputFormatters,
    super.keyboardAppearance,
    super.keyboardType,
    super.magnifierConfiguration,
    super.maxLength,
    super.maxLengthEnforcement,
    super.maxLines,
    super.minLines,
    super.mouseCursor,
    super.obscureText,
    super.obscuringCharacter,
    super.onAppPrivateCommand,
    super.onChanged,
    super.onEditingComplete,
    super.onFieldSubmitted,
    super.onSaved,
    super.onTap,
    // super.onTapAlwaysCalled,
    super.onTapOutside,
    super.readOnly,
    super.restorationId,
    super.scribbleEnabled,
    super.scrollController,
    super.scrollPadding,
    super.scrollPhysics,
    super.selectionControls,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.showCursor,
    super.smartDashesType,
    super.smartQuotesType,
    super.spellCheckConfiguration,
    // super.statesController,
    super.strutStyle,
    super.textAlign,
    super.textAlignVertical,
    super.textCapitalization,
    super.textDirection,
    super.textInputAction,
    super.undoController,
    super.validator,
    super.style = const TextStyle(fontSize: 16, color: Color(0xffcdcdcd)),
    super.decoration = const GymnasticTextInputDecoration(),
  });
}
