on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get

      - run: flutter build apk
      - name: Start release build
        run: flutter build appbundle
